src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints AS Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @Vich\Uploadable
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Veuillez entrez le title")
     */
    protected $title;

    /**
     * @Assert\File(
     *     maxSize="3M",
     *     mimeTypes={"image/png", "image/jpeg", "image/jpg"}
     * )
     * @Vich\UploadableField(mapping="post_image", fileNameProperty="imageName", size="imageSize")
     * @var File $imageFile
     */
    protected $imageFile;


    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    protected $imageSize;

    /**
     * @var string $imageName
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $imageName;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotNull(message="Veuillez entrez un contenu")
     */
    protected $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $created;


    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title", "id"}, separator="_", updatable=false)
     */
    protected $slug;


    /**
     * @var
     * @ORM\ManyToOne(targetEntity="App\Entity\Activity", inversedBy="posts")
     */
    protected $activity;


    public function __construct()
    {
        $this->created = new \DateTime('now');
    }


    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }


    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     * @throws \Exception
     */
    public function setImageFile(?File $image = null): void
    {
        $this->imageFile = $image;
        if (null !== $image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->created = new \DateTimeImmutable();
        }
    }
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function getUploadDir()
    {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'images/post';
    }

    protected function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../public/'.$this->getUploadDir();
    }

    /**
     * @return string
     */
    public function getAssertPath()
    {
        return $this->getUploadDir().'/'.$this->imageName;
    }

    public function getActivity(): ?Activity
    {
        return $this->activity;
    }

    public function setActivity(?Activity $activity): self
    {
        $this->activity = $activity;

        return $this;
    }
}

src/Entity/Solution.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints AS Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SolutionRepository")
 * @Vich\Uploadable
 */

class Solution
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Entrez le nom de la solution")
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name", "id"}, separator="_", updatable=false)
     */
    protected $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank(message="Entrez la description")
     */
    protected $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Coller la balise de partage des documents")
     */
    protected $reader;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $created;

    /**
     * @var
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="solutions")
     */
    protected $category;


    public function __construct()
    {
        $this->created = new \DateTime('now');
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getReader(): ?string
    {
        return $this->reader;
    }

    public function setReader(string $reader): self
    {
        $this->reader = $reader;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(?\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/SolutionType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Solution;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class SolutionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Choix de la Sous-Catégorie',
                'required' => true,
                'attr' => ['placeholder' => 'Choix de la Sous-Catégorie', 'class' => 'col-md-6']
            ])
            ->add('name', TextType::class, [
                'label' => 'Nom de la solution',
                'attr' => ['placeholder' => 'Entrez la solution']
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Entrez le contenu ici',
                'attr'  => ['placeholder' => 'Entrez le contenu ici', 'class' => 'editor']
            ])
            ->add('reader', TextType::class, [
                'label' => 'Intégrez le lien de partage de la documentation ici',
                'attr' => ['placeholder' => 'Coller le lien ici']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Solution::class,
        ]);
    }
}

src/Controller/SolutionController.php
<?php

namespace App\Controller;

use App\Entity\Solution;
use App\Form\SolutionType;
use App\Repository\SolutionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/solution")
 */
class SolutionController extends Controller
{
    /**
     * @Route("/", name="solution_index", methods="GET")
     */
    public function index(SolutionRepository $solutionRepository): Response
    {
        return $this->render('solution/index.html.twig', ['solutions' => $solutionRepository->findAll()]);
    }

    /**
     * @Route("/new", name="solution_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $solution = new Solution();
        $form = $this->createForm(SolutionType::class, $solution);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($solution);
            $em->flush();

            return $this->redirectToRoute('solution_index');
        }

        return $this->render('solution/new.html.twig', [
            'solution' => $solution,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="solution_show", methods="GET")
     */
    public function show(Solution $solution): Response
    {
        return $this->render('solution/show.html.twig', ['solution' => $solution]);
    }

    /**
     * @Route("/{id}/edit", name="solution_edit", methods="GET|POST")
     */
    public function edit(Request $request, Solution $solution): Response
    {
        $form = $this->createForm(SolutionType::class, $solution);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('solution_edit', ['id' => $solution->getId()]);
        }

        return $this->render('solution/edit.html.twig', [
            'solution' => $solution,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="solution_delete", methods="DELETE")
     */
    public function delete(Request $request, Solution $solution): Response
    {
        if ($this->isCsrfTokenValid('delete'.$solution->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($solution);
            $em->flush();
        }

        return $this->redirectToRoute('solution_index');
    }
}

templates/solution/_delete_form.html.twig
<form method="post" action="{{ path('solution_delete', {'id': solution.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ solution.id) }}">
    <button class="btn btn-float btn-danger"><i class="ti-trash"></i></button>
</form>

templates/solution/_form.html.twig
<div class="card card-round card-shadowed px-50 py-30 w-700px mb-0" style="max-width: 100%">
    <h5 class="text-uppercase">{{ 'Remplissez ou modifiez le Formulaire' }}</h5>
    <span class="badge badge-info">Taille Récommandée: Image Actualité <strong class="badge badge-danger">370x220</strong></span>
    <br>
    {{ form_start(form, {'attr': {'class': 'card', novalidate: 'novalidate'} } ) }}
    <h4>Lien ci-dessous pour le guide d'ajout de balise de document</h4>
    <strong><a href="https://pacificu.libguides.com/c.php?g=495911&p=3395956" target="_blank" style="text-decoration:underline">
    {{ 'Cliquez ici pour voir le Tuto pour l\'ajout de docs directement de google drive' }}</a></strong>
    <div class="form-group">
        {{ form_widget(form) }}
        {{ form_errors(form) }}
        <button class="btn btn-label {{ button_class|default('btn-info') }}">
            <label><i class="ti-save"></i></label>
            {{ button_label|default('Enregister') }}
        </button>
        <a class="btn btn-label btn-dark" href="{{ path('solution_index') }}">
            <label><i class="ti-arrow-left"></i></label>
            {{ 'Retour à la liste'}}
        </a>
    </div>
    {{ form_end(form) }}
</div>

templates/solution/edit.html.twig
{% extends 'admin.html.twig' %}
{% block title %} {{ 'Solutions' }} {% endblock %}
{% block body %}
    <div class="col-12">
        <div class="card">
            <header class="card-header">
                <h4 class="card-title">{{ 'Modifier Solutions'|upper }}</h4>
                {{ include('solution/_delete_form.html.twig') }}
            </header>
            <div class="card-body center-vh">
                {{ include('solution/_form.html.twig', {
                    'button_label': 'Mise à jour', 'button_class': 'btn-danger'
                })
                }}
            </div>
        </div>
    </div>
{% endblock %}

templates/solution/index.html.twig
{% extends 'admin.html.twig' %}
{% block title %} {{ 'Solutions' }} {% endblock %}
{% block body %}
    <div class="col-12">
        <div class="card">
            <header class="card-header">
                <h4 class="card-title">{{ 'Liste'|upper }}</h4>
                <a class="btn btn-label btn-info" href="{{ path('solution_new') }}">
                    <label><i class="ti-plus"></i></label>
                    {{ 'Ajouter un nouveau'}}
                </a>
            </header>
            <div class="card-body">
                <table class="table table-striped table-bordered" cellspacing="0" data-provide="datatables">
                    <thead>
                        <tr>
                            <th>{{ 'Nom' }}</th>
                            <th>{{ 'Sous-famille' }}</th>
                            <th>Created</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>{{ 'Nom' }}</th>
                            <th>{{ 'Sous-famille' }}</th>
                            <th>Created</th>
                            <th>actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    {% for solution in solutions %}
                        <tr>
                            <td>{{ solution.name }}</td>
                            <td>{{ solution.category.name }}</td>
                            <td>{{ solution.created ? solution.created|date('Y-m-d H:i:s') : '' }}</td>
                            <td>
                                <a href="{{ path('solution_show', {'id': solution.id}) }}" class="btn btn-primary">{{ 'Afficher' }}</a>
                                <a href="{{ path('solution_edit', {'id': solution.id}) }}" class="btn btn-danger">{{ 'Modifier' }}</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="9">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/solution/new.html.twig
{% extends 'admin.html.twig' %}
{% block title %} {{ 'Solutions' }} {% endblock %}
{% block body %}
    <div class="col-12">
        <div class="card">
            <header class="card-header">
                <h4 class="card-title">{{ 'Creér une Solutions'|upper }}</h4>
                <a class="btn btn-square btn-outline-danger" href="{{ path('solution_index') }}">
                    <label><i class="ti-na"></i></label>
                </a>
            </header>
            <div class="card-body center-vh">
                {{ include('solution/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/solution/show.html.twig
{% extends 'admin.html.twig' %}
{% block title %} {{ 'Solutions' }} {% endblock %}
{% block body %}
    <div class="col-6 col-md-offset-6">
        <div class="card">
            <header class="card-header">
                <h4 class="card-title">{{ 'Solutions détail'|upper }}</h4>
                {{ include('solution/_delete_form.html.twig') }}
            </header>
            <img class="card-img-top" src="{{ asset(solution.assertPath) }}" alt="Card image cap">
            <div class="card-body">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>{{ 'Sous-famille' }}</th>
                        <td>{{ solution.category.name }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'Nom' }}</th>
                        <td>{{ solution.name }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'Descript' }}</th>
                        <td>{{ solution.content }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'Document' }}</th>
                        <td>{{ solution.reader }}</td>
                    </tr>
                    <tr>
                        <th>{{ 'Date de creation' }}</th>
                        <td>{{ solution.created ? solution.created|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a class="btn btn-label btn-dark" href="{{ path('solution_index') }}">
                    <label><i class="ti-arrow-left"></i></label>
                    {{ 'Retour à la liste'}}
                </a>
                <a class="btn btn-label btn-danger" href="{{ path('solution_edit', {'id': solution.id}) }}">
                    <label><i class="ti-pencil-alt"></i></label>
                    {{ 'Modifier' }}
                </a>
            </div>
        </div>
    </div>
{% endblock %}